//
//  Copyright (c) 2017-2020 PSPDFKit GmbH. All rights reserved.
//
//  The PSPDFKit Sample applications are licensed with a modified BSD license.
//  Please see License for details. This notice may not be removed from
//  this file.
//

#pragma mark - Classes

#define PDFAction PDFXAction
#define PDFActionGoTo PDFXActionGoTo
#define PDFActionNamed PDFXActionNamed
#define PDFActionResetForm PDFXActionResetForm
#define PDFActionRemoteGoTo PDFXActionRemoteGoTo
#define PDFActionURL PDFXActionURL
#define PDFAnnotation PDFXAnnotation
#define PDFAnnotationPopup PDFXAnnotationPopup
#define PDFAppearanceCharacteristics PDFXAppearanceCharacteristics
#define PDFBorder PDFXBorder
#define PDFDestination PDFXDestination
#define PDFDocument PDFXDocument
#define PDFOutline PDFXOutline
#define PDFPage PDFXPage
#define PDFSelection PDFXSelection
#define PDFThumbnailView PDFXThumbnailView
#define PDFView PDFXView

#pragma mark - Protocols

#define PDFViewDelegate PDFXViewDelegate

#pragma mark - Notifications

#define PDFDocumentDidUnlockNotification PDFXDocumentDidUnlockNotification
#define PDFDocumentDidBeginFindNotification PDFXDocumentDidBeginFindNotification
#define PDFDocumentDidEndFindNotification PDFXDocumentDidEndFindNotification
#define PDFDocumentDidBeginPageFindNotification PDFXDocumentDidBeginPageFindNotification
#define PDFDocumentDidEndPageFindNotification PDFXDocumentDidEndPageFindNotification
#define PDFDocumentDidFindMatchNotification PDFXDocumentDidFindMatchNotification
#define PDFDocumentDidBeginWriteNotification PDFXDocumentDidBeginWriteNotification
#define PDFDocumentDidEndWriteNotification PDFXDocumentDidEndWriteNotification
#define PDFDocumentDidBeginPageWriteNotification PDFXDocumentDidBeginPageWriteNotification
#define PDFDocumentDidEndPageWriteNotification PDFXDocumentDidEndPageWriteNotification

#define PDFThumbnailViewDocumentEditedNotification PDFXThumbnailViewDocumentEditedNotification

#define PDFViewDocumentChangedNotification PDFXViewDocumentChangedNotification
#define PDFViewChangedHistoryNotification PDFXViewChangedHistoryNotification
#define PDFViewPageChangedNotification PDFXViewPageChangedNotification
#define PDFViewScaleChangedNotification PDFXViewScaleChangedNotification
#define PDFViewAnnotationHitNotification PDFXViewAnnotationHitNotification
#define PDFViewCopyPermissionNotification PDFXViewCopyPermissionNotification
#define PDFViewPrintPermissionNotification PDFXViewPrintPermissionNotification
#define PDFViewAnnotationWillHitNotification PDFXViewAnnotationWillHitNotification
#define PDFViewSelectionChangedNotification PDFXViewSelectionChangedNotification
#define PDFViewDisplayModeChangedNotification PDFXViewDisplayModeChangedNotification
#define PDFViewDisplayBoxChangedNotification PDFXViewDisplayBoxChangedNotification
#define PDFViewVisiblePagesChangedNotification PDFXViewVisiblePagesChangedNotification

#pragma mark - Other

#define kPDFDestinationUnspecifiedValue kPDFXDestinationUnspecifiedValue
